inherit_from: .rubocop_todo.yml

inherit_gem:
  simplycop: 
    - .simplycop.yml
    - .simplycop_performance.yml
    - .simplycop_security.yml
    - .simplycop_rspec.yml

AllCops:
  Exclude:
    - 'vendor/**/*'
