language: ruby
rvm:
  - 2.4
  - 2.5
  - 2.6
  - jruby

gemfile:
  - Gemfile

matrix:
  allow_failures:
  - rvm: jruby # Google protobuf, requirement for turnip 4 not compatible yet
    gemfile: Gemfile

script: bundle exec rspec spec
